# -*- coding: utf-8 -*-
"""Netflix_content.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYLBXzP_53sxGcvxh-m-K1RH3yCl8yU5
"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Nikita_DAUP/netflix_data.csv")

"""**STEP 1: Read CSV file**"""

df.head()

df.info()

df.shape

df.columns

"""**STEP 2: DATA CLEANING**"""

df.isnull().sum()

#DROP ROWS
df.dropna(inplace=True)

#FILLUP VALUES
df['director'].fillna("Unknown", inplace=True)

#REMOVE DUPLICATES
df.drop_duplicates(inplace=True)

#FIX DATA TYPE
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

#FOR INCONSISTENT DATA
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

#FOR INCONSISTENT LABEL
df['type'] = df['type'].str.strip()

"""**STEP 3:EXPLORATORY DATA ANALYSIS**"""

#1. Indicates Netflix focuses more on movie content
df['type'].value_counts().plot(kind='bar')
plt.title("Distribution of Content Type")
plt.xlabel("Type")
plt.ylabel("Count")
plt.show()

#2. Content production is geographically concentrated
df['country'].value_counts().head(10).plot(kind='barh')
plt.title("Top 10 Content Producing Countries")
plt.xlabel("Count")
plt.show()

#3. Rapid growth after ~2015
df['year_added'] = pd.to_datetime(df['date_added'], errors='coerce').dt.year
df['year_added'].value_counts().sort_index().plot()
plt.title("Content Added Over Time")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.show()

#4. Mature ratings (TV-MA) dominate
sns.countplot(x='rating', data=df)
plt.xticks(rotation=45)
plt.title("Content Rating Distribution")
plt.show()

#5. Most movies fall in 80–120 minutes range
df['duration_int'] = df['duration'].str.extract('(\d+)').astype(float)
df[df['type']=='Movie']['duration_int'].plot(kind='hist', bins=20)
plt.title("Movie Duration Distribution")
plt.xlabel("Minutes")
plt.show()

#6. Some countries produce mostly movies, others more TV shows
pd.crosstab(df['country'], df['type']).head(10).plot(kind='bar', stacked=True)
plt.title("Content Type by Country")
plt.show()

#7. Top Directors with Most Content
df['director'].value_counts().head(10).plot(kind='bar')
plt.title("Top Directors on Netflix")
plt.xticks(rotation=45)
plt.show()

#8. Certain genres dominate
df['listed_in'].value_counts().head(5).plot.pie(autopct='%1.1f%%')
plt.title("Top Genres Distribution")
plt.ylabel("")
plt.show()

#9. relationships between numerical features.
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""**STEP 5: CONCLUSION**

1.   Netflix content is dominated by movies
2.   Content production increased significantly after 2015
3.  USA/India contribute most content
4.   Mature content (TV-MA) is highly common

**STEP 6: DECISION MAKING**


1.   Focus more on high-demand genres
2.   Invest in countries producing more content
3.   Increase production in trending categories
4.  Adjust content ratings based on audience demand
"""

